package_name: house_price_predictor
mlflow_experiment_id: 6
mlflow_run_name: final_training
house_price_log_file: houseprice.log
raw_data_file: train.csv
clean_data_file: house_price_processed.pkl
train_file: train_data.pkl
train_y_file: train_y_data.pkl
test_file: test_data.pkl
test_y_file: test_y_data.pkl
columns_to_rename:
 BsmtFinSF1: BsmtFinSF
columns_to_convert_to_int:
 - BsmtFullBath
 - BsmtHalfBath
 - FullBath
 - HalfBath
 - KitchenAbvGr
 - Fireplaces
 - YrSold
target_variable: SalePrice
features_set:
 - OverallQual
 - OverallCond
 - age_at_sale
 - age_of_house_squared
 - house_have_remodel
 - GrLivArea
 - TotalBsmtSF
 - total_sf
 - ratio_finished_bsmt
 - basement_ratio
 - total_full_baths
 - total_half_baths
 - BedroomAbvGr
 - bedrooms_per_1ksf
 - bed_bath_ratio
 - has_garage
 - garage_finished
binary_features:
 - house_have_remodel
 - has_garage
 - garage_finished
linear_scaled_features:
 - GrLivArea
 - TotalBsmtSF
 - total_sf
preprocess_pipeline_name: house_price_preprocessor
preprocessor_model_name: house-price-preprocessor-sklean
preprocessor_alias: Production
model_name: house-price-model-lgbm
ml_model_alias: Production
model_type: tree
best_model: LightGBM
best_model_params:
 boosting_type: gbdt
 learning_rate: 0.05
 n_estimators: 100
 n_jobs: -1
 num_leaves: 35
